/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testservice_TestNative */

#ifndef _Included_com_example_testservice_TestNative
#define _Included_com_example_testservice_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testservice_TestNative
 * Method:    startAthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testservice_TestNative_startAthread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
